[#88-deployment]
= Deployment

include::chapter-include.adoc[]

[quote, John Augustus Shedd]
A ship in harbor is safe, but that is not what ships are built for.

TODO

== Iterative and Incremental Approach

TODO: intro to I&I.
TODO: warn against waterfall big bang projects.
It will take years. Plan ahead.
Just the intro. More details about the entire cycle in the next chapter.

TODO: IDM projects take a long time, split to iterations
TODO: Analyse, plan, prototype, execute, learn, repeat.

TODO: midPoint is built to support this approach, including open source (zero up-front license cost, subscriptions)

== Deployment and Operation Tooling

TODO: midPoint Studio
TODO: ninja
TODO: python CLI

== Environment

=== Relational Databases

TODO: Why relational database.
TODO: Supported relational databases.
TODO: universal (hibernate) repository, vs PostgreSQL

=== High Availability

TODO

=== Resources and Connectors

TODO: common connectors, support status

== Deployment Strategy

TODO: business first
TODO: start with normal mappings. Switch to strong.

TODO: devel, test and prod environments

TODO: configuration versioning


== Maintainability

Info: maintainable solution. First day is the day of the deployment.
TODO: you will need to proceed in iterations, it will take years.

== Good Practices

TODO

== Bad Practices

* Creating identifiers by using different "iterators", e.g. username jack123, mail jack.andrson.5@example.com
Reason: complex to remember, complex to diagnose, complex to configure and troubleshoot
Solution: go for jack.anderson.123@example.com or even better janderson8 and jack.anderson.8@example.com.

* TODO: user-user manager relation as bad practice. Use orgtree instead.

== Beware The Data

TODO: data are always wrong. Always.
People will tell you that they have good data.
They do not have good data.
No data will survive first contact with reality.
There will be conflicts.
There will be typos, mistakes, inaccuracies.
Good portion of data will be out of date.

Recommendation: proceed slowly.
Validate the data before rolling out.

=== Role Management

TODO: How to design and create roles.

Try to void application roles.
The purpose of IDM is to bridge applications.
Construction and entitlement associations can be used instead of application roles.
In theory.
Although you probably cannot avoid use of application roles entirely, as people will want to request application entitlements directly.
At least synchronize them automatically using generic sync.

=== Organizational Structure

TODO: quality varies wildly
TODO: try to reconstruct the real, practical organizational tree (not the formal one).

TODO: avoid user-manager method

== Integration

TODO: REST, Java client, Python client

== Work Organization

TODO: This is not a project, it is a program (see later). Proceed in steps, iterations, increments.

TODO: Good communication is absolutely essential.
Required information is seldom documented.
Difficulty for remote projects.
