[#88-deployment]
= Deployment

include::chapter-include.adoc[]

[quote, John Augustus Shedd]
A ship in harbor is safe, but that is not what ships are built for.

TODO

== Iterative and Incremental Approach

TODO: intro to I&I.
TODO: warn against waterfall big bang projects.
It will take years. Plan ahead.
Just the intro. More details about the entire cycle in the next chapter.

TODO: IDM projects take a long time, split to iterations
TODO: Analyse, plan, prototype, execute, learn, repeat.

TODO: midPoint is built to support this approach, including open source (zero up-front license cost, subscriptions)

== Before The Project

you need to know what you want to do.

Cheshire cat: If you do not know where you want to get, then it does not matter which way you go.

=== Proposal

Purchasing process is often seen as a battle between supplier and customer.
That is an efficient method to get a good _price_. Good for customer, that is.
But this is a terrible method if you need to get good _result_.

We like to see purchasing process as a dialog, as a cooperation rather than a battle.
TODO

TODO: RFP process is not ideal, but we have to live with it.
Avoid RFP if you can, try to have a dialog.

Writing RFP: Always prioritize the requirements.
Real priorities, setting everything to "Critical" will not work.
Outline a long-term plan (years)
Make the RFP short and efficient.
Human resources are limited, especially in IDM.
The longer the RFP is, the lower the chance that the good engineers won't have time to answer.
You want perfect IDM solution?
But that is extremely expensive.
Do you have the money?
What IDM solution would be _good enough_ for you?

Answering RFP: Try to find out the priorities (questions).
Try to propose iterative approach, even if the requests looks like waterfall.
Waterfall does not make sense, such project would fail anyway.

*Always* do PoC. Internally or externally. 2 weeks are usually appropriate.

General: Build up trust.
Look at our source code, commits, number of developers, etc.
Look at our bugtracking, see how bugs are fixed.
Smart small (PoC), grow up.


=== Skills and Consulting Capacity

TODO: trainings (ideally before project)
Make sure there is someone that can help you (Evolveum support subscription is not meant for this).

=== Plan and Vision

TODO: short-term plan (1-3 iterations)
long-term vision (2-7 years)

== Deployment and Operation Tooling

TODO: midPoint Studio
TODO: ninja
TODO: python CLI

== Environment

=== Relational Databases

TODO: Why relational database.
TODO: Supported relational databases.
TODO: universal (hibernate) repository, vs PostgreSQL

=== High Availability

TODO

=== Resources and Connectors

TODO: common connectors, support status

== Deployment Strategy

TODO: business first
TODO: start with normal mappings. Switch to strong.

TODO: devel, test and prod environments

TODO: configuration versioning


== Maintainability

Info: maintainable solution. First day is the day of the deployment.
TODO: you will need to proceed in iterations, it will take years.


== Beware The Data

TODO: data are always wrong. Always.
People will tell you that they have good data.
They do not have good data.
No data will survive first contact with reality.
There will be conflicts.
There will be typos, mistakes, inaccuracies.
Good portion of data will be out of date.

HR data are usually quite good, but they are also wrong.

Recommendation: proceed slowly.
Validate the data before rolling out.

== Iteration Structure

TODO: flexible proportions.
First iterations will be heavier on analysis
Later iterations will be heavy on testing.

=== Analysis

TODO: short intro to iteration analysis

=== Implementation

TODO: include: data migration

=== Testing and Fixing

TODO

== Analytic Techniques

Therefore, one has to ask the right (detailed) questions and wait for the right (even more detailed) answers.

Asking the right questions is both art and science.
Identity management projects are dealing with automating the user management processes which haven't been automated (or attempted to, or failed to do so) before.
Be prepared for a lot of very general, incomplete and inconsistent information.
Keep asking.

=== Get The Big Picture

Listen to the customer.
TODO: make sure you understand the (business) goal of the solution


=== Understand Current Environment

TODO: what is here today

=== Understand The Goal

TODO: what has to be achieved

=== Administrator Questionnaires

TODO: sysadmin questionnaires

TODO: Do not expect too much from the questionnaires.
You will get a couple of good answers.
Most answers will have only partial data, they will not be very precise.
Some admins will nor respond at all.

=== Data Clash

TODO: just pull in the data, see how they look like, try to correlate

=== Reverse Engineering

TODO: look at the data, look at HR records, try to figure out how they were created

=== Analysis Paralysis

TODO: Do not try to analyze too much.
People are people.
They say one thing, but the reality is different.
If there is a database column that is supposed to be ASCII7 form of user's full name, created as concatenation of first and last name, then there is almost certain probability that it contains value `Count Félix Teleke of Tölökö III, KBE`.
Do not rely on analytical results completely.

== Data Structures

=== Role Management

TODO: How to design and create roles.

Try to void application roles.
The purpose of IDM is to bridge applications.
Construction and entitlement associations can be used instead of application roles.
In theory.
Although you probably cannot avoid use of application roles entirely, as people will want to request application entitlements directly.
At least synchronize them automatically using generic sync.

=== Organizational Structure

TODO: quality varies wildly
TODO: try to reconstruct the real, practical organizational tree (not the formal one).

TODO: avoid user-manager method

== Integration

TODO: REST, Java client, Python client

== Work Organization

TODO: This is not a project, it is a program (see later). Proceed in steps, iterations, increments.

TODO: Good communication is absolutely essential.
Required information is seldom documented.
Difficulty for remote projects.

== Good Practices

TODO

== Bad Practices

* Creating identifiers by using different "iterators", e.g. username jack123, mail jack.andrson.5@example.com
Reason: complex to remember, complex to diagnose, complex to configure and troubleshoot
Solution: go for jack.anderson.123@example.com or even better janderson8 and jack.anderson.8@example.com.

* TODO: user-user manager relation as bad practice. Use orgtree instead.


== TODO

Plan ahead, especially if you need new features.
MidPoint has 6 months development cycles.
The backlog has years and years worth of improvements ideas, therefore it is perhaps quite natural that roadmap is a bit overcrowded.
It takes some planning to get your features on midPoint roadmap, even if you have the funds for their development.

Even bugfixes can take weeks to months to get fixed. Plan ahead. Test early. Proceed in iterations.

TODO: warn against over-use of AI

Data sources:

(Business to Employee, B2E)
HR system is usually a good start.
Look for data sources for contractors & temporary workers.
You may not find any.
Consider that IDM may become the source.

Look for organizational structure sources.
You will probably find several sources, all of them useless.
It would either not reflect reality, or it will not be machine-processable.
Most likely both.


(Business to Business, B2B)
Look for data source for partners.
In fact, you are looking for two data sources:

* Partner _organizations_

* Partner _users_ (employees/contractors of partners)

You would like for the partner _user_ data to come (directly or indirectly) from partner's HR system.
Two options:

* SSO/Federation, just in time provisioning, deprovisioning problem, etc.
* Delegated administration

Most likely, you will need both.

You may need a "sponsor" for each partner or even user.
Sponsor is your employee/contractor that is responsible for the partner/user.

TODO: Academia, distributed research teams, vitual organizations, all that mess.

(Business to Consumer/Customer/Citizen, B2C, CIAM)
Usually on a bigger scale. Needs scalability.
Less value per identity, needs cost-efficient solution.

Different lifecycle, usually governed by the user rather than given by the organization.
Self-service is a must.

Data protection and privacy very important.


Do not automate everything.
It is too much work, too much maintenance.
Prioritize.
Automate frequently-used systems (large populations).
Automate frequently-changed systems (fluctuation).
Automate sensitive systems (seucirity, accountability).
Automate day-one systems (mail, productivity).
Automate systems that generate helpdesk load.

However, think about security and accountibility.
Semi-manual approach may be a good compromise (CSV exports).

=== Password Management

Avoid storing passwords in IDM, if you can.

Inconsistent password policies.
The best way is to make them as consistent as possible, work with security team.


=== Entitlement Management

Resource-side entitlements: there may be _a lot_ of them.
Managing everything is likely to be a complex burden.
There will be thousands of privileges, in hundreds of systems.
The low-level privileges often needs very intimate understanding of the system/application where they are used, including understanding of the _configuration_ of the application.
Identity management team has almost zero chance to get this right.

Try to manage high-level privileges in target systems, such as groups or roles.

Separate the problem into two parts:

* privileges->groups/roles on resource side: responsibility of system admin

* user -> (IDM) roles -> resource-side entitlements (groups/roles): responsibility of IDM team

Choose the right level of abstraction.
The "entitlements" should have a business meaning, rather than technological meaning.
Such as job, work position, bussiness function, responsibility, ability for meaningful action.
E.g. "branch supervisor" rather than "access-list-123"

== Conclusion

This chapter is not complete. Maybe it will never be complete.
Similarly to midPoint project, this chapter is developed in an iterative and incremental fashion.
