[#88-iam-program]
= IAM Program

include::chapter-include.adoc[]

[quote, First Law of Mentat, "Dune by Frank Herbert"]
A process cannot be understood by stopping it. Understanding must move with the flow of the process, must join it and flow with it.

TODO: intro

this chapter is about IAM in general.

== This Is Not A Project

TODO: IAM is a program, not a project. But there may be an initial deployment project, migration projects and so on.
TODO: how to make analysis for an deployment project

TODO: IAM projects fail, because IAM is not a project.
It is a program.
If you think about IAM deployment as a project, you are doomed to failure.

TODO: Similar to security program

== Convergences

TODO: proceed in iterations: iterative and incremental process. No big bangs.
TODO: deployment efficiency, reuse, 20-80
TODO: Igor: “Even on target system level, Target system shall be connected in iterations, improve on new data quality first, then take on the existing data and as business first we have to be sure we are going to improve and not destroy existing state, last do deprovisioning/disabling”


=== Analyze

TODO
TODO: Good communication is absolutely essential.
Required information is seldom documented.
There is a lot of "historical practices", nobody may know why is it done the way that it is done.
Difficulty for remote projects.

=== Prototype

TODO: prototype before committing to specific platform.

=== Plan

It will take years. Plan ahead.

TODO: rolling wave planning

Features that you need now, features that you will need later down the road.
Unlike commercial products, you can influence roadmap of open source systems by investing effort and/or money.

=== Execute

TODO: Develop, Test and Deploy

=== Learn

TODO: gather feedback

=== Repeat

TODO

== Organization

TODO: build or buy: build solution internally or get turnkey solution.
Neither work and both work.

Extreme inhouse or turnkey won't work.

But "assisted" inhouse or turnkey will both work.

TODO: board-level sponsorship for the program, similar to security.
But it is seldom achievable, as identity does not get sufficient attention.
Data protection?

Leadership is essential. There must be a leader in target organization.

== Identity Management and Governance

TODO: this chapter is about IAM in general.
Here are the aspects that are specific for identity management (IGA).

=== Garbage In, Garbage Out

TODO: Analysis: things to focus on for identity management

TODO: Source data quality: garbage in, garbage out. The source data quality is usually low. Do not believe “oh, we have precise HR data”. They don’t.

TODO: Igor: “HR data are hard to be trusted, quality of HR data is questionable. Some actions are hard to be done in acceptance, like full data visibility is not permitted by security.”


== TODO

Info: maintainable solution. First day is the day of the deployment.
