[#92-additional-information]
= Additional Information

include::chapter-include.adoc[]

[quote,Leto II,"Children of Dune by Frank Herbert"]
Logic's useless unless it's armed with essential data.

We have tried to make this book as comprehensive as possible.
However, no book can possibly include all the information that an identity management engineer would ever need.
Therefore, this chapter describes the sources of additional information about midPoint.

== MidPoint Documentation Site

MidPoint documentation site (a.k.a. _docs_) is the most comprehensive information about midPoint.
This is where all the midPoint reference documentation is stored.
Yet, there is even more.
There is connector documentation, midPoint architecture, developer documentation, midPoint internals and all kinds of information including midPoint release planning and roadmap.
Everything is public.

However, the _docs_ are so comprehensive that it is often not entirely easy to find the right page.
We have done what we could to organize the information.
The pages are organized hierarchically.
Many pages have "See Also" section that points to additional information.
Yet, the practice shows that if you want to find something in the docs, you need to have at least a faint idea what you are looking for.
This book should give you that idea what to look for.
If you know what you are looking for, then the _docs_ search bar is your friend.
If you enter the correct search term, then there is high probability that you will quickly find the right page.

URL: https://docs.evolveum.com/[https://docs.evolveum.com/]

== Samples

The midPoint projects maintains quite a rich collection of samples.
These are sample resource definitions, role and organizational structure examples and other various samples.
They are usually provided in the XML form.
The samples are maintained in a separate project on GitHub.
Those samples are also part of midPoint distribution package.

URL{nbsp}(version{nbsp}{midpointversion}):{nbsp}https://github.com/Evolveum/midpoint-samples/support-{midpointversion}/master/samples[https://github.com/Evolveum/midpoint-samples/support-{midpointversion}/master/samples] +
URL{nbsp}(latest{nbsp}development{nbsp}version):{nbsp}https://github.com/Evolveum/midpoint-samples/tree/master/samples[https://github.com/Evolveum/midpoint-samples/tree/master/samples]

== Book Samples

This book contains many examples and configuration snippets that are taken from various places.
Some smaller snippets are taken from midPoint docs or from the sample files (see above).

Some chapters contain mostly complete configurations of the midPoint deployment.
These configurations have a separate folder in the midPoint samples.
Look for a `samples` folder in the github repository in which source code of this books is maintained.
All the important files used in this book are there, sorted by chapter number.
There are also special-purpose _docker compose_ configurations that simulate configuratin used in this book.
The _readme_ files in individual directories provide more details.

URL{nbsp}(version{nbsp}{midpointversion}):{nbsp}https://github.com/Evolveum/midpoint-book/tree/support-{midpointversion}/samples[https://github.com/Evolveum/midpoint-book/tree/support-{midpointversion}/samples] +
URL{nbsp}(latest{nbsp}development{nbsp}version):{nbsp}https://github.com/Evolveum/midpoint-book/tree/master/samples[https://github.com/Evolveum/midpoint-book/tree/master/samples]

== Story Tests

MidPoint developers like to create and maintain complete end-to-end automated tests.
These tests are usually inspired by real-world midPoint deployments.
We call them _story tests_.
These tests are important to maintain midPoint quality and continuity.
They are also excellent source of inspiration, and they have often proved useful as examples of midPoint configuration.

* Documentation:{nbsp}https://docs.evolveum.com/midpoint/reference/samples/story-tests/[https://docs.evolveum.com/midpoint/reference/samples/story-tests/]
* Code{nbsp}and{nbsp}configuration:{nbsp}https://github.com/Evolveum/midpoint/tree/master/testing/story[https://github.com/Evolveum/midpoint/tree/master/testing/story]

== MidPoint Mailing List

MidPoint project attracted a vibrant community during the years.
The main community communication channel is _midPoint mailing list_ `midpoint@lists.evolveum.com`.
The mailing list is used for announcements, user suggestions, and also for _community support_.
The mailing list is used to ask questions about midPoint.
Experienced community members usually answer these questions and provide pointers to additional information.
The whole midPoint development team is also subscribed to the mailing list, and they provide answers when needed.
However, this is a best effort service.
Please do not abuse this communication channel and try to keep the following community guidelines:

. *Be polite.* Mailing list is a best effort service.
Nobody is (directly) paid to answer mailing list questions.
The engineers that answer the questions are doing that in addition to their day-to-day responsibilities, they are doing that because they want to help the community.
Therefore, if you are asking for help, do so politely.
If you are answering a question, please respect other members.
Everybody started somewhere, it is natural that novice users do not know everything.
Please tolerate the differences in skill sets.

. *Do some research before asking a question.*
Do not ask trivial question that can be easily answered by googling the question, by searching for it in the midPoint _docs_ or mailing list archive.
If you are getting an error, try to read error message very carefully, and try to think about the possible causes.
Try to experiment with the configuration a bit.
Look at the troubleshooting section in the _docs_.
Spend at least a couple of minutes to make your own research before asking the question.
If that research does not provide the answer, then it is a good question for the mailing list.

. *Provide context.*
If your post looks like "_my midpoint is broken, please help_" then it is very unlikely that you will get any answers.
Try to describe your problem in more details.
Make sure to describe relevant bits of your configuration.
Be sure to include error message.
Look in the log files if necessary.
Most importantly of all: state your goal, describe what you are trying to achieve.
Maybe the root of your problem is that you are using completely wrong approach.
The community may point your nose in the right direction - but only if they know what is your goal.

. *Give back.*
Mailing list is not one way communication channel where users ask questions and developers answer them.
There is already a significant body of knowledge distributed among community members that are not midPoint developers.
If you adhere to these guidelines and ask a question, it will most likely be answered.
However, for that to happen there needs to be someone who is answering.
Therefore, do not just ask the questions.
If you know the answer to the question that someone else asks, then please go ahead and answer it.
Do not worry that your answer may not be perfect.
Even a partial answer will be greatly appreciated by any novice user.
Simply speaking: Do not only take from the community.
Try to repay what the community gave you.

You may also be tempted to send your questions directly to Evolveum or midPoint developers.
However, the developers have many midPoint users, partners, customers and contributors to deal with in their day-to-day job.
The first responsibility of any midPoint core developer is to make sure that midPoint development continues.
The developers naturally prefer to spend time doing tasks that bring funding to the midPoint project.
Therefore, the developers strictly prioritize the communication.
Answers to midPoint subscribers are the highest priority, mailing list is second and answers to private messages from the community are absolutely the lowest priority.
We prefer efficient spread of knowledge about midPoint.
Mailing list is good for that, but private communication is not.
That’s the primary reason for this priority setup.
Besides, if you contact a developer directly, then only that developer can answer your question.
However, if you send the question to the mailing list, there are more people that can potentially answer the question.
Therefore, unless you have active subscription, the mailing list is your best option.

Mailing list URL: http://lists.evolveum.com/mailman/listinfo/midpoint

== Evolveum Video Channel

Some of the midPoint related information was recorded in a form of videos.
There are also recordings of midPoint-related Evolveum webinars, presentation and talks.
All videos as published on Evolveum YouTube channel.

Evolveum YouTube channel URL: https://www.youtube.com/@Evolveum[https://www.youtube.com/@Evolveum]

== Evolveum Blog

Vast majority of midPoint development and maintenance is conducted by Evolveum team.
The people of Evolveum present their professional opinions by the means of Evolveum blog.
The blog is very technology-friendly.
The information provided on the blog goes often quite deep.
This is also a channel how Evolveum shares information about midPoint development plans and business activities related to midPoint.
It is a very valuable resource for anyone that has a professional interest in midPoint.

Evolveum blog URL: https://evolveum.com/blog/

== Social Networks

Evolveum is moderately active on social networks, publishing information about the company and midPoint.
Content published on social networks is made suitable for this environment, therefore it is usually lighter that can be consumed quickly.
Despite that, it is well worth subscribing to be kept updated with latest news.

LinkedIn: https://www.linkedin.com/company/evolveum[https://www.linkedin.com/company/evolveum] +
Twitter(X): https://twitter.com/evolveum[https://twitter.com/evolveum] +
Facebook: https://www.facebook.com/evolveum[https://www.facebook.com/evolveum] +
Instagram: https://www.instagram.com/evolveum_midpoint/[https://www.instagram.com/evolveum_midpoint/]
